Remove `std::mutex()` from list-initialization
Remove the `std::mutex()` constructor call from list-initialization in
`ucxx::Endpoint`. This is totally unnecessary and may cause issues with
some compilers (or compiler options):

```
...
error: function "std::mutex::mutex(const std::mutex &)" (declared at line 94 of /opt/conda/envs/base/lib/gcc/x86_64-conda-linux-gnu/11.4.0/include/c++/bits/std_mutex.h) cannot be referenced -- it is a deleted function
```