fix(libucxx_tests): tests require RMM flag
Before this change, trying to build `libucxx_tests` without also running
`libucxx_python` would fail with

```
$BUILD_PREFIX/bin/../lib/gcc/x86_64-conda-linux-gnu/13.3.0/../../../../x86_64-conda-linux-gnu/bin/ld: tests/CMakeFiles/UCXX_TEST.dir/utils
.cpp.o: in function `createCudaContextCallback(void*)':
utils.cpp:(.text._Z25createCudaContextCallbackPv+0x4): undefined reference to `cudaFree'
```