Move [[nodiscard]] to non-friend declaration (#339)
`[[nodiscard]]` attribute does not have effect on `friend` declaration, and Clang compiler rejects it:
```
ucxx/cpp/include/ucxx/context.h:75:3: error: an attribute list cannot appear here
   75 |   [[nodiscard]] friend std::shared_ptr<Context> createContext(ConfigMap ucxConfig,
      |   ^~~~~~~~~~~~~
```

It also triggers `-Wattributes` in GCC:
```
ucxx/cpp/include/ucxx/context.h:75:49: warning: attribute ignored [-Wattributes]
   75 |   [[nodiscard]] friend std::shared_ptr<Context> createContext(ConfigMap ucxConfig,
      |                                                 ^~~~~~~~~~~~~
ucxx/cpp/include/ucxx/context.h:75:49: note: an attribute that appertains to a friend declaration that is not a definition is ignored
```

Move the `[[nodiscard]]` attribute to the non-friend declaration.

Authors:
  - Yuan Tong (https://github.com/tongyuantongyu)

Approvers:
  - Peter Andreas Entschev (https://github.com/pentschev)

URL: https://github.com/rapidsai/ucxx/pull/339